version: '3.8'
services:
  scylla:
    build: .
    container_name: scylla-db
    ports:
      - "9042:9042"  # CQL
      - "7000:7000"  # intra-node communication
      - "7001:7001"  # TLS intra-node
      - "7199:7199"  # JMX
      - "10000:10000" # Alternator (REST API, optional)
    environment:
      - SCYLLA_CLUSTER_NAME=heimdall-cluster
      - SCYLLA_DC=dc1
      - SCYLLA_RACK=rack1
    command: --smp 1 --memory 750M --overprovisioned 1
    volumes:
      - scylla-data:/var/lib/scylla
volumes:
  scylla-data:
