# Dockerfile for gRPC server
FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN pip install --upgrade pip && pip install poetry && poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

COPY src/heimdall_bifrost/listener ./listener
COPY src/heimdall_bifrost/db/scylla.py ./db/scylla.py

EXPOSE 50051
CMD ["python", "listener/grpc_server.py"]
