apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall-grpc
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: heimdall-grpc
  template:
    metadata:
      labels:
        app: heimdall-grpc
    spec:
      containers:
        - name: heimdall-grpc
          image: "{{ .Values.grpc.repository }}:{{ .Values.grpc.tag }}"
          imagePullPolicy: {{ .Values.grpc.pullPolicy }}
          ports:
            - containerPort: 50051
