# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import listener.metric_pb2 as metric__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in metric_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class metricServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMetric = channel.unary_unary(
                '/heimdall.metricService/SendMetric',
                request_serializer=metric__pb2.MetricRequest.SerializeToString,
                response_deserializer=metric__pb2.MetricResponse.FromString,
                _registered_method=True)


class metricServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMetric(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_metricServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMetric': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMetric,
                    request_deserializer=metric__pb2.MetricRequest.FromString,
                    response_serializer=metric__pb2.MetricResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'heimdall.metricService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('heimdall.metricService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class metricService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMetric(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heimdall.metricService/SendMetric',
            metric__pb2.MetricRequest.SerializeToString,
            metric__pb2.MetricResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
